environment:
  matrix:
    - PYTHON: "C:\\PYTHON27"
    - PYTHON: "C:\\PYTHON27-x64"
    - PYTHON: "C:\\PYTHON34"
    - PYTHON: "C:\\PYTHON34-x64"
    - PYTHON: "C:\\PYTHON35"
    - PYTHON: "C:\\PYTHON35-x64"
    - PYTHON: "C:\\PYTHON36"
    - PYTHON: "C:\\PYTHON36-x64"
build: off
before_test:
  - "Start-FileDownload https://raw.githubusercontent.com/RedFantom/python-package-ci/master/ci.py"
test_script:
  - "%PYTHON%\\python.exe ci.py"
artifacts:
  - path: "/dist/*.whl"
deploy:
  provider: GitHub
  auth_token:
    secure: QimY++/91urL/oMJL/q2zYFqc1C7747HguEaIbPQovtC3zG8CK+TiCmFOCXy1D6e
  artifact: "/dist/*.whl"
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
